# Generated by Django 5.2.8 on 2025-11-20 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('FRQ', 'Free Response'), ('TRUE_FALSE', 'True/False'), ('CLOZE', 'Cloze'), ('MATCHING', 'Matching'), ('REASONING', 'Reasoning')], max_length=20)),
                ('prompt', models.TextField()),
                ('bloom_level', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(blank=True, max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('correct_answer', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['quiz', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=5)),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quizzes.question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('settings', models.JSONField()),
                ('custom_instructions', models.TextField(blank=True)),
                ('output_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.ManyToManyField(related_name='quizzes', to='content.contentsource')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.quiz'),
        ),
    ]
